[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nd_line"
version = "0.2.0"  # This is the only place version should be hard coded
authors = [
  { name="Daniel Marshall", email="dpm42@duke.edu" },
]
description = "Interpolate points on an n-dimensional line by euclidean arc length"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent"
]
dependencies = [
  "numpy",
  "scipy"
]

[project.optional-dependencies]
dev = [
  "pre-commit>=4.0,<5",
  "pytest>=8,<10",
  "commitizen>=4,<5",
]

[project.urls]
"Homepage" = "https://github.com/thedannymarsh/nd_line"
"Bug Tracker" = "https://github.com/thedannymarsh/nd_line/issues"
"Changelog" = "https://github.com/thedannymarsh/nd_line/blob/main/CHANGELOG.md"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.flynt]
line-length = 120

[tool.docformatter]
wrap-summaries = 0
wrap-descriptions = 0
in-place = true

[tool.mypy]
no_namespace_packages = true

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_provider = "pep621"

[tool.semantic_release]
allow_zero_version = true
branch = "main"
build_command = "pip install build && python -m build"
commit_message = "chore(release): {version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "conventional"
commit_parser_options = {parse_squash_commits = true, ignore_merge_commits = true}
major_on_zero = true
no_git_verify = true
tag_format = "v{version}"
upload_to_release = true
version_toml = [
  "pyproject.toml:project.version"
]

[tool.semantic_release.changelog]
exclude_commit_patterns = [
  '''chore(?:\([^)]*?\))?: .+''',
  '''ci(?:\([^)]*?\))?: .+''',
  '''refactor(?:\([^)]*?\))?: .+''',
  '''style(?:\([^)]*?\))?: .+''',
  '''test(?:\([^)]*?\))?: .+''',
  '''build\((?!deps\): .+)'''
]
mode = "update"

[tool.semantic_release.remote]
type = "github"
